### ISSUE TITLE
Take a look at http://docs.withdraft.com/

### ISSUE THREAD

**Issue by davidbgk** [dtc-innovation/research#2]
Link: https://draftin.com/

Doc: http://docs.withdraft.com/

Blog: I can't find anymore the announcement on https://m.signalvnoise.com/@natekontny too bad because it was interesting :(

Cons: Side-project of @natekontny

**Comment by davidbgk** [comment]
Found it! https://m.signalvnoise.com/i-can-t-sing-6c11cdf93dfc

**Comment by thom4parisot** [comment]
C'est propre :-)

Je le mettrai en annexe (car side project)—ça peut toujours servir en complément.

Merci pour la suggestion !

**Comment by thom4parisot** [comment]
Au détour d'une recherche je découvre [Penflip](https://www.penflip.com) aka. [GitHub for Writers](http://www.madebyloren.com/github-for-writers) 👍

**Comment by thom4parisot** [comment]
J'en parle ici c45069be6b322aec5c174266dd52c9f1336f6163

Merci encore :-)
